# vim:set ft=sh:

# Clear Screen
alias cls='clear'
# List symbolic links
alias lsl='ls -lhaF --color | grep "\->"'
# Shutdown
alias TurnOff='sudo shutdown -h now'
# Aliases to apt-get
alias Install-pkg='sudo apt-get install'
alias Upgrade-pkg='sudo apt-get install --only-upgrade'
alias Remove-pkg='sudo apt-get remove'
alias Search-pkg='sudo apt-cache search'
alias Check-pkg='dpkg -l | grep'
# Virtual Environmets
alias ActEnv='source activate'
alias DeactEnv='source deactivate'
# Nemo (File manager)
alias n.='nemo .'
# Edit this file
alias eba='vim ~/.bash_aliases'
# .bashrc related
alias emybrc='vim ~/.mybashrc'
alias ebrc='vim ~/.bashrc'
alias sbrc='source ~/.bashrc'
# powerline-shell config file
alias epls='vim ~/.config/powerline-shell/config.json'
alias evrc='vim ~/.vim/vimrc'
